# Generated by Django 2.2 on 2019-06-16 11:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
